In [2]:
import numpy as np

In [5]:
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [9]:
arr.reshape(-1, 1)

array([[1],
       [2],
       [3]])

In [10]:
print(arr[:, np.newaxis])

[[1]
 [2]
 [3]]


In [28]:
from sklearn.linear_model import LinearRegression

In [16]:
X = arr[:, np.newaxis]

In [29]:
model = LinearRegression(fit_intercept=True)

In [19]:
model.fit(X, y)

NameError: name 'y' is not defined

In [20]:
print(model.coef_[0], model.intercept_)

AttributeError: 'LinearRegression' object has no attribute 'coef_'

In [21]:
model = LinearRegression(fit_intercept=True)

In [22]:
model.fit(X, y)

NameError: name 'y' is not defined

In [30]:
X_fit = [[15], [-19]]

In [31]:
y_fit = model.predict(X_fit)

NotFittedError: This LinearRegression instance is not fitted yet. Call 'fit' with appropriate arguments before using this method.

In [32]:
from sklearn.preprocessing import PolynomialFeatures

In [33]:
poly = PolynomialFeatures(degree=3, include_bias=True)
X = np.array([[2], [3], [4]])
print(poly.fit_transform(X))

[[ 1.  2.  4.  8.]
 [ 1.  3.  9. 27.]
 [ 1.  4. 16. 64.]]


In [34]:
X_poly = poly.fit_transform(X)
model = LinearRegression(fit_intercept=False)
model.fit(X_poly, y)

NameError: name 'y' is not defined

In [35]:
print(model.coef_)

AttributeError: 'LinearRegression' object has no attribute 'coef_'

In [37]:
poly = PolynomialFeatures(degree=11, include_bias=True)
X_poly = poly.fit_transform(X)
model = LinearRegression(fit_intercept=False)
model.fit(X_poly, y)

NameError: name 'y' is not defined

In [41]:
xb = np.random.normal(3, 1, 6)
xb

array([1.83199799, 1.41501619, 3.01127535, 3.33484981, 2.89184076,
       3.60859897])